// gs_blake2s.h - BLAKE2s, from RFC 7693, because a commitment needs a hash that
// is hard to work backwards and `gs_world_hash` is not one.
//
// `gs_world_hash` is FNV-1a. That is exactly right for what it does - noticing
// that two machines have stopped agreeing - and useless for a promise, because
// a promise has to be one the promiser cannot wriggle out of afterwards.
// Committing to an input means publishing something that pins it down without
// revealing it, and then revealing it later; with a hash anyone can invert, the
// commitment pins nothing.
//
// **Not invented here.** BLAKE2s is specified in RFC 7693, is the hash named by
// the Noise suite this project has already chosen for its transport, and comes
// with published test vectors. `tests/test_gearstick.c` checks this
// implementation against them and against a set generated by an independent one
// - Python's `hashlib` - because an implementation of a standard that has only
// been checked against itself is an implementation of something else.
//
// Integers only, no allocation, no SDL. It lives in core because the thing that
// needs it - the rollback session in gs_net.c - does, and core links nothing.
#ifndef GS_BLAKE2S_H
#define GS_BLAKE2S_H

// **`<stdbool.h>` explicitly.** In C23 `bool` is a keyword and this include is
// a no-op; MSVC's C23 is partial and it is not, which is why `windows-clang`
// exists as the documented fallback. Every other header in core picks this up
// from `gs_common.h`; this one includes nothing of ours on purpose, so it says
// so itself.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define GS_BLAKE2S_BYTES 32
#define GS_BLAKE2S_BLOCK 64

typedef struct gs_blake2s {
    uint32_t h[8];
    uint64_t counted;                    // bytes taken in, total
    uint8_t  buf[GS_BLAKE2S_BLOCK];
    size_t   held;                       // bytes in buf not yet compressed
    uint8_t  out_len;
} gs_blake2s;

// Streaming, for a caller that has the message in pieces. `out_len` is 1 to 32.
void gs_blake2s_init(gs_blake2s *s, uint8_t out_len);
void gs_blake2s_update(gs_blake2s *s, const void *data, size_t len);
void gs_blake2s_final(gs_blake2s *s, uint8_t *out);

// The whole message at once, which is what every caller here actually wants.
void gs_blake2s_hash(uint8_t *out, uint8_t out_len, const void *data, size_t len);

// The first eight bytes of the digest, little-endian, as one number. A
// truncation, and it is worth being clear about what it costs: sixty-four bits
// is not enough to resist a determined search for a *collision*, and is far more
// than enough to resist finding a second message matching one given digest,
// which is the property a commitment actually rests on.
uint64_t gs_blake2s_u64(const void *data, size_t len);

#endif // GS_BLAKE2S_H
