#!/usr/bin/env python3
"""Bake the trigonometric tables src/core/gs_tables.h.

The tables are generated and committed rather than computed at start-up, for the
same reason the rest of the simulation is integers: a table built at run time is
a table a different libm can build differently, and then two machines disagree
about where a car is. Generated here in Python's arbitrary precision, rounded
once, and checked into git - so every platform reads the same numbers.

Two tables:

  gs_sintab    a quarter turn of sine in Q16.16. The other three quadrants come
               from symmetry in gs_sin().

  gs_atantab   arctan(2^-i) in the same 65536-steps-per-turn angle units, for
               the CORDIC vectoring loop in gs_atan2(). Sixteen entries is one
               per bit of the 16-bit angle; past that the terms round to zero
               and contribute nothing.

Re-run after changing SIN_BITS and commit the result. CI re-bakes and diffs, so
the committed file cannot drift from what this script produces.
"""
import math
import pathlib

SIN_BITS = 10                    # 1024 steps in a quarter turn
SIN_STEPS = 1 << SIN_BITS
ONE = 1 << 16
TURN = 65536

sin_vals = [min(ONE, round(math.sin(i * (math.pi / 2) / SIN_STEPS) * ONE))
            for i in range(SIN_STEPS + 1)]

ATAN_LEN = 16
atan_vals = [round(math.atan(2.0 ** -i) / (2 * math.pi) * TURN) for i in range(ATAN_LEN)]

out = [
    "// gs_tables.h - GENERATED by tools/make_tables.py. Do not edit.",
    "//",
    "// Committed rather than computed at start-up: a table built at run time is",
    "// a table a different libm can build differently, and determinism is the",
    "// one thing this simulation cannot trade away. See gs_fixed.h.",
    "#ifndef GS_TABLES_H",
    "#define GS_TABLES_H",
    "",
    '#include "core/gs_common.h"',
    "",
    "// A quarter turn of sine in Q16.16, %d steps plus the endpoint." % SIN_STEPS,
    "#define GS_SINTAB_BITS %d" % SIN_BITS,
    "#define GS_SINTAB_LEN  %d" % (SIN_STEPS + 1),
    "",
    "static const int32_t gs_sintab[GS_SINTAB_LEN] = {",
]
for i in range(0, len(sin_vals), 8):
    out.append("    " + ", ".join("%6d" % v for v in sin_vals[i:i + 8]) + ",")
out += [
    "};",
    "",
    "// arctan(2^-i), in angle units of 65536 to the turn, for CORDIC vectoring.",
    "#define GS_ATANTAB_LEN %d" % ATAN_LEN,
    "",
    "static const int32_t gs_atantab[GS_ATANTAB_LEN] = {",
]
for i in range(0, len(atan_vals), 8):
    out.append("    " + ", ".join("%5d" % v for v in atan_vals[i:i + 8]) + ",")
out += ["};", "", "#endif // GS_TABLES_H", ""]

path = pathlib.Path(__file__).resolve().parent.parent / "src" / "core" / "gs_tables.h"
path.write_text("\n".join(out))
print("wrote %s (%d sine, %d arctan)" % (path, len(sin_vals), len(atan_vals)))
