# Libsodium.cmake - build the pinned libsodium submodule.
#
# **libsodium ships no CMake.** Upstream builds with autotools on Unix and
# MSBuild on Windows, and this project builds with CMake and Ninja on three
# platforms. So the sources are compiled here rather than upstream's build being
# driven from here: an ExternalProject would need autotools on the developer's
# machine and a different build system on Windows, and would put a configure
# script between a source file and the object it produces.
#
# **Nothing in ext/ is modified.** This file lives outside it and names the
# submodule's sources; the submodule stays exactly what upstream tagged. That is
# the rule ext/README.md states and this is what keeping it looks like when the
# dependency does not speak the same build system.
#
# Every source is compiled, rather than the handful this project uses being
# picked out. A subset that is wrong links cleanly and behaves subtly
# differently, which is the worst failure available in a cryptographic library.
# The cost is build time, once.

function(gs_add_libsodium)
    set(_root "${CMAKE_CURRENT_SOURCE_DIR}/ext/libsodium")
    if(NOT EXISTS "${_root}/src/libsodium/include/sodium.h")
        message(FATAL_ERROR
            "ext/libsodium is empty. Run:\n"
            "  git submodule update --init --depth 1 ext/libsodium")
    endif()

    # version.h is generated by upstream's configure. Two numbers and a string,
    # taken from the tag this submodule is pinned at.
    set(VERSION "1.0.20")
    set(SODIUM_LIBRARY_VERSION_MAJOR 26)
    set(SODIUM_LIBRARY_VERSION_MINOR 2)
    set(SODIUM_LIBRARY_MINIMAL_DEF "")
    configure_file("${_root}/src/libsodium/include/sodium/version.h.in"
                   "${CMAKE_CURRENT_BINARY_DIR}/sodium-generated/sodium/version.h"
                   @ONLY)

    file(GLOB_RECURSE _sodium_sources CONFIGURE_DEPENDS
         "${_root}/src/libsodium/*.c")

    add_library(gearstick_sodium STATIC ${_sodium_sources})

    # The generated version.h includes "export.h", which upstream satisfies by
    # installing both into the same `sodium/` directory. It cannot be written
    # next to its sibling here - ext/ is not modified - so the directory holding
    # the sibling goes on the search path instead, which reproduces the layout
    # an installed libsodium presents.
    target_include_directories(gearstick_sodium
        PUBLIC
            "${_root}/src/libsodium/include"
            "${_root}/src/libsodium/include/sodium"
            "${CMAKE_CURRENT_BINARY_DIR}/sodium-generated"
            "${CMAKE_CURRENT_BINARY_DIR}/sodium-generated/sodium")

    # Built into this program rather than shipped as a library, so nothing is
    # exported and nothing declares a DLL interface.
    target_compile_definitions(gearstick_sodium PUBLIC SODIUM_STATIC=1)
    target_compile_definitions(gearstick_sodium PRIVATE
        CONFIGURED=1
        DEV_MODE=0
        _GNU_SOURCE=1)

    # **Deliberately not passed through gs_configure().** Vendored code is not
    # ours to warn about, and -Wconversion on somebody else's audited library
    # produces a wall of noise about code that is correct. The same rule the
    # SDL and SQLite submodules are built under.
    set_target_properties(gearstick_sodium PROPERTIES
        C_STANDARD 99
        C_EXTENSIONS ON
        POSITION_INDEPENDENT_CODE ON)

    if(MSVC)
        target_compile_options(gearstick_sodium PRIVATE /w)
    else()
        target_compile_options(gearstick_sodium PRIVATE -w)
    endif()

    message(STATUS "gearstick: libsodium ${VERSION} from the ext/ submodule")
endfunction()
